using NpgsqlTypes;

namespace CareerHub.Api.Models;

// WHAT CHANGED FROM 2.3:
// - SearchVector added — a computed, stored tsvector column generated by the database
//   from Title and Description. The GIN index on this column enables full-text search.
//   The application never writes to this property — the database generates it automatically.
//
// No data annotations — all configuration is in CareerHubDbContext Fluent API.

public class JobListing
{
    public JobListing() { }

    public JobListing(
        Guid id, string title, string description, Guid companyId,
        string location, JobType type, decimal? salaryMin, decimal? salaryMax,
        DateTime postedAt, bool isActive, DateTime closingDate,
        JobListingStatus status = JobListingStatus.Active)
    {
        Id          = id;
        Title       = title;
        Description = description;
        CompanyId   = companyId;
        Location    = location;
        Type        = type;
        SalaryMin   = salaryMin;
        SalaryMax   = salaryMax;
        PostedAt    = postedAt;
        IsActive    = isActive;
        ClosingDate = closingDate;
        Status      = status;
    }

    public Guid Id { get; set; }
    public string Title { get; set; } = string.Empty;
    public string Description { get; set; } = string.Empty;

    public Guid CompanyId { get; set; }
    public Company Company { get; set; } = null!;

    public string Location { get; set; } = string.Empty;
    public JobType Type { get; set; }
    public decimal? SalaryMin { get; set; }
    public decimal? SalaryMax { get; set; }
    public DateTime PostedAt { get; set; } = DateTime.UtcNow;
    public bool IsActive { get; set; } = true;
    public DateTime ClosingDate { get; set; }
    public JobListingStatus Status { get; set; } = JobListingStatus.Active;

    // Computed, stored tsvector column — generated by the database from Title and Description.
    // The GIN index on this column makes full-text search use an index scan instead of a seq scan.
    // private set: the application never writes to this — EF Core reads it from the database.
    public NpgsqlTsVector SearchVector { get; private set; } = null!;

    public ICollection<Application> Applications { get; set; } = [];
}
